# Example alertmanager.yml configuration
#
# See https://prometheus.io/docs/alerting/configuration/ for Alertmanager configuration syntax and built-in receivers.
# Currently, these include email, HipChat, PagerDuty, OpsGenie, Slack, VictorOps, and WeChat.
route:
  group_by: ['alertname']
  group_wait: 45s
  group_interval: 10m
  repeat_interval: 6h
  receiver: 'first-responders'

receivers:

  - name: 'first-responders'

#    email_configs:
#      - to: 'user@example.com'
#        send_resolved: false
#        from: 'no-reply@example.com'
#        smarthost: 'outbound.example.com:25'

#    webhook_configs:
#      - send_resolved: false
#        url: http://errbot:3141/alerrt/username/domain.com/
