x-deploy-policy: &x-deploy-policy
  replicas: 1
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

configs:
  # Prometheus
  prometheus-config:
    name: prometheus-config-v1
    file: configs/prometheus.yml
  # Scrape configs
  scrape-configs-docker:
    name: prometheus-scrape-configs-docker-v1
    file: configs/scrape_configs/docker.yml
  scrape-configs-dockerswarm:
    name: prometheus-scrape-configs-dockerswarm-v1
    file: configs/scrape_configs/dockerswarm.yml
  # Rules
  alerting-rules-node:
    name: prometheus-alerting-rules-node-v1
    file: configs/rules/node.yml
  alerting-rules-service:
    name: prometheus-alerting-rules-service-v1
    file: configs/rules/service.yml
  alerting-rules-task:
    name: prometheus-alerting-rules-task-v1
    file: configs/rules/task.yml
  
  # Alertmanager
  alertmanager.yml:
    name: alertmanager-v1.0.yml
    file: configs/alertmanager.yml

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus-{{.Task.Slot}}
    user: root
    command:
      - "--log.level=info"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=10GB"
      - "--storage.tsdb.retention.time=10d"
    networks:
      - promstack
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
      # Scrape configs
      - source: scrape-configs-docker
        target: /etc/prometheus/scrape_configs/docker.yml
      - source: scrape-configs-dockerswarm
        target: /etc/prometheus/scrape_configs/dockerswarm.yml
      # Rules
      - source: alerting-rules-node
        target: /etc/prometheus/rules/node.yml
      - source: alerting-rules-service
        target: /etc/prometheus/rules/service.yml
      - source: alerting-rules-task
        target: /etc/prometheus/rules/task.yml
    deploy: *x-deploy-policy
    logging: *x-default-logging

  alertmanager:
    image: prom/alertmanager:latest
    hostname: alertmanager-{{.Task.Slot}}
    command:
      - "--log.level=info"
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    networks:
      - promstack
    ports:
      - 9093:9093
    volumes:
      - alertmanager:/alertmanager
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    deploy: 
      <<: *x-deploy-default
      labels:
        io.prometheus.job: "alertmanager"
    logging: *x-logging-default

volumes:
  prometheus:
  alertmanager:

networks:
  promstack:
