groups:
  - name: services
    rules:
      # CPU usage
      
      # Memory usage
      - alert: service_high_memory_usage_9g
        expr: sum(container_memory_rss{name!~"", container_label_com_docker_swarm_service_name!~""}) by (container_label_com_docker_swarm_service_name) > 9e+09
        for: 1m
        annotations:
          description: '{{ $labels.container_label_com_docker_swarm_service_name }} memory usage is {{ humanize $value }}.'
          summary: Memory alert for service '{{ $labels.container_label_com_docker_swarm_service_name }}'

      # Network usage
      - alert: service_high_network_receive_10GB_5m
        expr: sum(rate(container_network_receive_bytes_total{name!~"", container_label_com_docker_swarm_service_name!~""}[1m]) * 60) by (container_label_com_docker_swarm_service_name) > 10e+09
        for: 5m
        annotations:
          description: '{{ $labels.container_label_com_docker_swarm_service_name }} network usage is {{ humanize $value }}.'
          summary: Network alert for service '{{ $labels.container_label_com_docker_swarm_service_name }}'

      - alert: service_high_network_transmit_10GB_5m
        expr: sum(rate(container_network_transmit_bytes_total{name!~"", container_label_com_docker_swarm_service_name!~""}[1m]) * 60) by (container_label_com_docker_swarm_service_name) > 10e+09
        for: 5m
        annotations:
          description: '{{ $labels.container_label_com_docker_swarm_service_name }} network usage is {{ humanize $value }}.'
          summary: Network alert for service '{{ $labels.container_label_com_docker_swarm_service_name }}'
